code/modules/world_save/map_storage.dm
=> Makes saving faster (maybe)

code/modules/world_save/map_storage.dm
=> Maybe makes stuff work

code/modules/world_save/map_storage.dm
=> no message

code/modules/world_save/map_storage.dm
To utilize best, save world, close, delete map contents, reopen, loadworld
=> Super quick save, super slow load.

code/modules/world_save/map_storage.dm
=> Quick Save AND Quick Load!

code/modules/world_save/map_storage.dm
=> Wip referenced storage

code/game/jobs/job_controller.dm, code/game/machinery/cryopod.dm, code/game/machinery/telecomms/telecomunications.dm, code/modules/client/preference_setup/loadout/loadout.dm, code/modules/mob/observer/ghost/ghost.dm, code/modules/organs/external/wounds/wound_types.dm, code/modules/world_save/map_storage.dm
=> Maybe fixes bugs

code/game/atoms_movable.dm
=> Reworks z edge throw

code/game/machinery/bioprinter.dm, code/game/mecha/mecha.dm, code/game/turfs/turf.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm, code/modules/virus2/isolator.dm
=> Maybe fixes blood runtimes, and mecha runtimes

interface/skin.dmf
=> Updates Interface

interface/skin.dmf
=> Adds hover info again

code/game/machinery/cryopod.dm, code/game/objects/items/blueprints.dm, code/modules/item_worth/worths_list.dm, interface/skin.dmf
=> Upgrades blueprints, makes them work instantly, and modifies cryopods

interface/skin.dmf
=> Adds tooltip

code/game/machinery/atmoalter/canister.dm
Adds the ability to weld a canister and turn it into steel.
=> Weld Canister

code/game/gamemodes/gameticker.dm
=> Removing CT and GM Auto Vote

code/controllers/voting.dm
=> Attempt at removing auto crew transfer

code/game/machinery/atmoalter/canister.dm
I.. Forgot to end my statement breaking some parts of canisters.
=> Patch to fix canisters

code/game/objects/structures/crates_lockers/closets/gimmick.dm, code/game/objects/structures/crates_lockers/closets/job_closets.dm, code/game/objects/structures/crates_lockers/closets/l3closet.dm, code/game/objects/structures/crates_lockers/closets/malfunction.dm, code/game/objects/structures/crates_lockers/closets/secure/bar.dm, code/game/objects/structures/crates_lockers/closets/secure/cargo.dm, code/game/objects/structures/crates_lockers/closets/secure/engineering.dm, code/game/objects/structures/crates_lockers/closets/secure/freezer.dm, code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm, code/game/objects/structures/crates_lockers/closets/secure/personal.dm, code/game/objects/structures/crates_lockers/closets/secure/scientist.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/game/objects/structures/crates_lockers/closets/utility_closets.dm, code/game/objects/structures/crates_lockers/crates.dm
=> Locker madness

code/game/machinery/doors/simple.dm
=> Checks for door locks

code/game/machinery/doors/airlock.dm
=> Missing var

code/modules/organs/internal/liver.dm, persistentss13.dme
=> Removes dehydration

code/modules/client/preferences_savefile.dm, code/modules/mob/new_player/new_player.dm
Alright turns out the last one just tried to find the gear for the dummy rather than the player. Whoops. This should work.
=> Actually fixes survival gear

code/datums/supplypacks/medical.dm, code/datums/supplypacks/operations.dm, code/datums/supplypacks/supply.dm, code/game/machinery/autolathe_datums.dm, code/game/objects/structures/crates_lockers/closets/job_closets.dm, code/modules/materials/material_recipes.dm, code/modules/paperwork/filingcabinet.dm, code/modules/projectiles/projectile/energy.dm, code/modules/research/designs.dm, code/modules/telesci/gps.dm
=> Fixed stuff, added 2 cargo packs

code/game/machinery/portable_turret.dm, code/game/machinery/turret_control.dm, code/game/objects/structures/crates_lockers/closets.dm, code/modules/mob/living/bot/bot.dm, nano/templates/turret_control.tmpl
=> Updates turrets for persistence

code/modules/materials/material_recipes.dm
=> Let engineers make sinks

code/game/machinery/wall_frames.dm
=> Add a normal /obj/item/frame/sink

code/modules/materials/material_recipes.dm
Reorganizes bathroom components
=> Organize fixtures, add shower, fix kitchensink

code/modules/materials/material_recipes.dm
Let people make normal sinks in addition to kitchen ones.
=> Add a normal sink frame

code/modules/clothing/clothing.dm, code/modules/clothing/head/misc_special.dm
You guys missed this one by a matter of hours when you split from bay.
Stolen from:
https://github.com/Baystation12/Baystation12/pull/19699
=> Fixes Mask Toggling

code/modules/hydroponics/seed_datums.dm
I don't know how I missed this when I first made peppercorn.
=> Peppercorn Actually has Pepper in it Now

code/game/machinery/cryo.dm, code/modules/modular_computers/computers/modular_computer/hardware.dm, code/modules/modular_computers/computers/modular_computer/interaction.dm, code/modules/reagents/Chemistry-Machinery.dm, code/modules/reagents/dispenser/dispenser2.dm, code/modules/research/rdconsole.dm, code/modules/virus2/curer.dm, code/modules/virus2/diseasesplicer.dm, code/modules/virus2/dishincubator.dm, code/modules/virus2/isolator.dm, code/modules/xenoarcheaology/tools/artifact_harvester.dm, code/modules/xenoarcheaology/tools/geosample_scanner.dm
* Changed many devices that eject something to eject into the user's hand if it is empty.
=> Added eject into hand to many devices

code/datums/supplypacks/medical.dm, code/datums/supplypacks/miscellaneous.dm, code/datums/supplypacks/supply.dm
- Add tabletop gaming crate (dice in all shapes, paper)
- Add cowboy hats to the costume crate randomized list
- Add a crate of medibelts
- Correctly sell 20 glowsticks for 20x
=> Assorted Supply Crate improvements

code/datums/supplypacks/supply.dm, code/modules/power/lighting.dm
They work the same as normal lights, but with a different color. Ideal for your rave lair!
=> Add colored light tubes and colored light bulbs to supply

code/datums/supplypacks/miscellaneous.dm, code/datums/supplypacks/operations.dm, code/modules/clothing/under/accessories/badges.dm, code/modules/clothing/under/accessories/ties.dm
- Adds the Beret Crate, for ordering lots of luxury berets. So soft and French!
- Adds the expensive, possibly jewelry-filled Luxury Crate
- Adds the Journalist Crate, for budding correspondents
- Removes access checks for holobadges
=> Berets, Earrings, Journalism, Law

code/datums/supplypacks/supply.dm, code/game/objects/structures/barsign.dm, code/game/objects/structures/crates_lockers/closets/utility_closets.dm, code/modules/materials/material_recipes.dm
- Orderable: Janicart Crate
- Barsign access restrictions have been reduced.
- Buildable: Book Binder
- Buildable: Wheelchair
- Buildable: Fire Extinguisher Wall Cabinet
- Buildable: Medical Wall Cabinet
- Buildable: Shipping Wall Cabinet
- Buildable: Fire Safety Wall Cabinet
- Buildable: Linen Bin
- Buildable: Dresser
- Buildable: Dog Bed
- Buildable: Morgue Tray
=> More Buildables

code/modules/research/rdconsole.dm
A tiny change that everyone has been looking forward to.
=> Change R&D console access

code/game/objects/items/devices/radio/radio.dm
=> Should fix radio encryptions

code/game/mecha/equipment/tools/tools.dm, code/game/mecha/mecha.dm
Clicking on a Hoverpod with a grabbed person will now attempt to stuff the target into any available passenger compartment.
=> Hoverpod Passenger Compartment Stuffing

code/modules/research/designs.dm
=> Added cryo_cell to designs.dm

code/datums/supplypacks/hospitality.dm, code/datums/supplypacks/miscellaneous.dm, code/datums/supplypacks/security.dm, code/modules/clothing/under/miscellaneous.dm
Adds a bulk clothes crate (x10 random clothing or jacket) and a worryingly expensive imported cigar crate. Also lets security specifically order orange jumpsuits.
=> Add bulk clothes crate and cigar crate

code/game/machinery/computer/guestpass.dm, code/game/objects/items/weapons/storage/wallets.dm, code/modules/integrated_electronics/assemblies.dm, code/modules/integrated_electronics/input_output.dm, code/modules/mob/holder.dm
=> Should fix turrets part 2(?)

code/modules/paperwork/handlabeler.dm
Allows the removal of labels by clicking again with an active hand labeler
=> Label Removal

code/datums/supplypacks/hospitality.dm
Adds a crate of assorted posters (x4) so you don't have to sift through other art supplies.
=> Add poster crate

code/game/machinery/hologram.dm, code/game/objects/items/weapons/circuitboards/other.dm
Fixes bug where holopads would not do anything when clicked on. Buffed long range holopads significantly while making them slightly more difficult to make.
=> Fixes holopads

code/datums/supplypacks/hydroponics.dm, code/modules/reagents/reagent_dispenser.dm
=> Make watertanks and beerkegs exportable

code/datums/supplypacks/medical.dm, code/game/machinery/autolathe_datums.dm
- Removed 2 Anesthetic tanks from the Cargo order, added 2 Medical Masks to compensate
- Adds new tools, including dolls, lipstick, combs and water balloons.
=> Changes to Anesthetics shipment, additions to the Autolathe

code/game/machinery/OpTable.dm, code/game/machinery/Sleeper.dm, code/game/machinery/adv_med.dm, code/game/machinery/resleever.dm
* Addresses medical inconsistencies laid out in https://github.com/Persistent-SS13/Persistent-Bay/issues/146
=> Medical consistency

code/datums/supplypacks/security.dm
This code change gives prisoners some shoes to wear.
=> Give prisoners some shoes

code/datums/supplypacks/atmospherics.dm, code/game/machinery/portable_turret.dm, nano/templates/turret_control.tmpl
Adds range option for turret, with maximum range remaining the same as current
Buffs turret health
Turrets now require plasteel to construct.
=> Adds options for turrets and buffs them slightly. Fixes sublimator typo

code/game/machinery/portable_turret.dm, nano/templates/turret_control.tmpl
Turrets now check faction and access properly
=> Fixes turrets

code/_helpers/global_access.dm, test/check-paths.sh, test/run-test.sh
=> Fixes Travis Part 2

code/modules/reagents/Chemistry-Recipes.dm
You can now make soap. This uses the same method for making dough (combine reagents in a container and the item will appear on the floor beneath you).
Soap | Ingredients
------------ | -------------
Normal Soap | 1 Glycerol + 1 Space Cleaner + 1 Water
Gold Soap | 1 Glycerol + 1 Space Cleaner + 1 Gold
Nanotrasen Soap | 1 Glycerol + 1 Space Cleaner + 1 Phoron
Syndicate Soap | 1 Glycerol + 1 Space Cleaner + 1 Blood
=> Add soapmaking

code/datums/supplypacks/operations.dm, code/modules/reagents/Chemistry-Recipes.dm
=>  Slight fix to an error made on last commit, adds CMO varient of the RD coat to Cargo.

code/game/turfs/simulated/wall_icon.dm, code/modules/construction/girders.dm
=>  Icon and Lighting generation tweaks/fixes

code/_helpers/atmospherics.dm, code/modules/atmospherics/atmospherics.dm, code/modules/atmospherics/components/binary_devices/binary_atmos_base.dm, code/modules/atmospherics/components/trinary_devices/filter.dm, code/modules/atmospherics/components/trinary_devices/trinary_base.dm, code/modules/atmospherics/components/unary/unary_base.dm, code/modules/atmospherics/pipes.dm
Allows gas analyzers to display the gas mixtures contained in unary, binary, and trinary devices. Adds mole count to gas analyzers
=> Adds gas analyzer abilities and fixes Hydrogen filtering bug

code/game/turfs/simulated/wall_icon.dm
=>  Might fix walls

code/_helpers/functional.dm, code/game/mecha/combat/combat.dm, code/game/mecha/equipment/tools/medical_tools.dm, code/game/mecha/mecha.dm, code/game/mecha/mecha_control_console.dm, code/modules/atmospherics/components/omni_devices/filter.dm, code/modules/overmap/events/event.dm
Replaces some (reserved by 512) keywords to make it so we don't immediately fail to compile for 512.
=> Makes Us 512 Compatible

code/_helpers/global_access.dm, test/check-paths.sh, test/run-test.sh
=> Travis Hotfix

code/modules/materials/materials.dm
=> Fixes Some Missing Commas

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
=> Hotfix for Indentation Runtime

code/game/objects/items/weapons/material/shards.dm, code/game/objects/structures/window.dm, code/modules/materials/materials.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm, code/modules/reagents/Chemistry-Recipes.dm
=> Fixes Everything?

code/game/machinery/OpTable.dm
Breaks the lingering pull when you drag someone onto the operating whilst pulling them.
This seemed to screw with surgery success.
=> Break pull when dragging someone onto operating table

code/game/machinery/Sleeper.dm
Fixes one of the issues here: https://github.com/Persistent-SS13/Persistent-Bay/issues/195
=> Fixed sleeper beaker issue

code/modules/reagents/Chemistry-Machinery.dm
=> Fixes Grinder Bug

code/_helpers/atmospherics.dm
Fixes a bug where the gas analyzer would improperly round gas percentages, preventing output.
=> Fixes gas analyzer bug

code/game/jobs/job_controller.dm, code/game/machinery/adv_med.dm, code/game/objects/items/devices/scanners.dm, code/game/objects/items/weapons/tools.dm, code/modules/organs/external/_external.dm, code/modules/organs/external/_external_damage.dm, code/modules/organs/external/head.dm, code/modules/organs/external/standard.dm, code/modules/organs/external/wounds/wound.dm, code/modules/organs/external/wounds/wound_types.dm, code/modules/organs/internal/_internal.dm, code/modules/organs/internal/appendix.dm, code/modules/organs/internal/brain.dm, code/modules/organs/internal/eyes.dm, code/modules/organs/internal/kidneys.dm, code/modules/organs/internal/liver.dm, code/modules/organs/internal/lungs.dm
Organs can now heal minor damage on their own over a long period of time. However, if they heal naturally (without any medical aid) then they will develop scarring, which decreases their maximum health and may have other undesirable side effects.
Humans no longer breathe out excess toxins. (i.e. no longer flood surgery rooms with N2O)
If you really want to, you can amputate someone's lower body and they won't immediately die. They'll still die really quickly though.
Your head is now repairable.
People with nearsightedness no longer spawn with glasses, in response to scarred eyes giving you nearsightedness.
Brain's Process() proc isn't nearly as monolithic.
The organ scarring is mine, but a big chunk of the other stuff was ported from the following Bay PRs: …
=> Permanent Organ Damage, Breathing Fixes, Other Organ Changes

code/modules/organs/internal/_internal.dm
Merj ASAP pls.
Temporarily comments out scarring until I can un-fuck it.
=> Temporary Organ Fix

code/game/objects/items/weapons/storage/storage_ui/default.dm
Related to recent bag clicking code.
=> Fix to memory leak.

code/modules/world_save/map_storage.dm
=> Trying to make loading less ram intensive

code/modules/world_save/map_storage.dm
=> More Load changes..

code/datums/supplypacks/materials.dm
Changing profit margin from averaging .5~.6 to roughly 1 by altering steel price again.
=> Increasing profit margin

test/check-paths.sh
#232 caused an error with Travis. This fixes that.
=> Fixes Travis Error

code/_helpers/global_access.dm, code/datums/supplypacks/engineering.dm, code/datums/supplypacks/medical.dm, code/datums/supplypacks/operations.dm, code/datums/supplypacks/security.dm, code/game/objects/items/devices/PDA/radio.dm, code/modules/client/preference_setup/general/01_basic.dm, code/modules/client/preference_setup/general/02_language.dm, code/modules/client/preference_setup/general/03_body.dm, code/modules/client/preference_setup/general/06_flavor.dm, code/modules/client/preference_setup/global/01_ui.dm, code/modules/client/preference_setup/global/03_language.dm, code/modules/client/preference_setup/global/05_ooc.dm, code/modules/client/preference_setup/skills/skills.dm, code/modules/power/generator.dm, code/modules/research/designs.dm, code/modules/world_save/map_storage.dm, code/unit_tests/autolathe_tests.dm, code/unit_tests/map_storage.dm, code/unit_tests/override_tests.dm, code/unit_tests/~unit_test_types.dm, persistentss13.dme, test/check-paths.sh, test/run-test.sh
Integrates some autolathe/protolathe tests.
Re-Enables cargo tests and changes the crates of a couple packs to keep it from failing.
Fixes TEG construction.
Fixes integrated radio deletion.
Integrates some basic Save/Load tests.
Makes preferences more consistent, using the `to_file` and `from_file` procs rather than `<<` and `>>`.
Fixes and re-enables the override tests.
If you run `run-test.sh` with bash and without a `TEST` var, it will allow you to input one.
=> You Merely Adopted The Travis; I Was Born In It, Molded By It

code/_macros.dm, code/game/objects/items/devices/whistle.dm, code/game/objects/items/weapons/autopsy.dm, code/modules/client/preference_setup/general/05_background.dm, code/modules/clothing/clothing.dm, code/modules/mob/grab/grab_datum.dm, code/modules/mob/living/carbon/human/human_helpers.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/living/carbon/human/whisper.dm, code/modules/mob/living/say.dm, code/modules/mob/mob_helpers.dm, code/modules/modular_computers/file_system/crew_record.dm, code/modules/organs/external/_external.dm, code/modules/organs/internal/brain.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm, code/modules/reagents/reagent_containers/food/snacks.dm, code/modules/recycling/sortingmachinery.dm, code/modules/surgery/bones.dm, code/modules/surgery/encased.dm, code/modules/surgery/generic.dm, code/modules/surgery/implant.dm, code/modules/surgery/organs_internal.dm, code/modules/surgery/other.dm, code/modules/surgery/robotics.dm
Fixes the Incision Management System (#240)
Fixes Whisper Encoding
Fixes Perscription Mesons
Mechs Can No Longer Enter Disposals
Fixes Offhand Grab Staying After Throwing Main Grab
Fixes Clamping of Bleeders (#231)
Makes it so pizza and other slice-able foods won't eat your knife if you're on harm intent (#72)
Makes it so fingerless gloves won't protect you from shock
Fixes the Hailer
Fixes the Brain Being Able to Heal Past 100%
Fixes Stuttering
Fixes the Text Starring Procs
Fixes the Encoding of Crew Records
Fixes Religion Being Double-Sanitized in Saves
Fixes the Cryo Injection Rate
=> Squashes a Bunch of Bugs

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
They're now in-line with our server.
=> Updates Github Templates

CODE_OF_CONDUCT.md
It adds a formalized set of contribution rules and guidelines so people can't try to rules-lawyer a message on the PR screen.
=> Adds a Code of Conduct for Contributions

code/game/turfs/simulated/wall_attacks.dm, code/game/turfs/simulated/wall_icon.dm, code/modules/construction/girders.dm
=>  Wall tweaks

code/_global_vars/configuration.dm
=> Fixes Time Bug

code/modules/surgery/organs_internal.dm
You will no longer be able to attach two hearts, eight kidneys, forty lungs, etc.
=> Fixes Multi-Organ Bug

code/modules/client/preferences_savefile.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species/species.dm
=> Probably Fixes Everything Spawning With a Stack

.travis.yml
The version of Travis we were running has been deprecated for a while, so I'm moving us over to their new environment. The new parameter will reduce message spam with the new version, which is what prevented us from switching earlier.
=> Updates Travis to the Latest Environment

code/game/shuttle_engines.dm, code/modules/factions/bluespace_satellite.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/shuttles/shuttle_console.dm, nano/templates/bridge_computer.tmpl
Everything except them moving, I'll do that soon
=> 90% of the shuttle update

code/modules/factions/bluespace_satellite.dm, code/modules/shuttles/shuttle.dm, code/modules/shuttles/shuttle_console.dm, nano/templates/bridge_computer.tmpl
should be everything required to build a shuttle and even launch it, but i want to test it on the main serv
=> Lots of shuttle things to test..

code/modules/factions/bluespace_satellite.dm, code/modules/shuttles/shuttle_console.dm, nano/templates/bridge_computer.tmpl
=> Small shuttle fixes

code/game/jobs/access.dm, code/game/objects/items/weapons/cards_ids.dm, code/modules/factions/bluespace_satellite.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/shuttles/shuttle.dm, code/modules/shuttles/shuttle_console.dm, nano/templates/bridge_computer.tmpl
shuttles should load properly now, cleans up the menu slightly, adds a bit of warmup time that will hopefully let the sound play
=> shuttle polish part 1

code/modules/shuttles/shuttle.dm, code/modules/shuttles/shuttle_console.dm
=> Shuttle fixes

code/_helpers/turfs.dm, code/game/jobs/_access_defs.dm, code/game/objects/items/weapons/circuitboards/other.dm, code/game/shuttle_engines.dm, code/modules/factions/bluespace_satellite.dm, code/modules/factions/faction.dm, code/modules/lighting/lighting_overlay.dm, code/modules/shuttles/shuttle.dm, code/modules/shuttles/shuttle_console.dm, nano/templates/docking_beacon.tmpl, nano/templates/faction_core.tmpl
=> More Shuttle changes

code/game/objects/items/weapons/circuitboards/other.dm, code/modules/factions/bluespace_satellite.dm, code/modules/research/designs.dm, code/modules/shuttles/shuttle_console.dm
=> Adds the designs

code/modules/factions/bluespace_satellite.dm, code/modules/modular_computers/file_system/programs/generic/supply2.dm, nano/templates/supply.tmpl
=> Small shuttle fix, Cargo Logging

code/modules/modular_computers/file_system/programs/generic/supply2.dm
=> small supply computer change

code/modules/modular_computers/file_system/programs/generic/records.dm
=> Small records fix

code/modules/mining/mine_turfs.dm
=> Small change, to preserve old asteroid turfs

code/game/objects/structures/lattice.dm
=> mad at baystation

code/game/objects/structures/lattice.dm
=> Travis fix..

code/game/machinery/pipe/construction.dm, code/game/objects/structures/lattice.dm, code/game/turfs/flooring/flooring_premade.dm, code/modules/mining/mine_turfs.dm
=> More improvements, wires and pipes on asteroid turf

code/game/jobs/access.dm, code/game/objects/items/robot/robot_parts.dm, code/game/objects/items/robot/robot_upgrades.dm, code/game/objects/items/weapons/cards_ids.dm, code/modules/emotes/definitions/_mob.dm, code/modules/factions/bluespace_satellite.dm, code/modules/mob/living/carbon/lace/lace.dm, code/modules/mob/living/carbon/lace/say.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/research/designs.dm
=> Lots of good robot upgrades, and a shuttle fix

code/_macros.dm, code/game/machinery/portable_turret.dm
Hostile animals are now shot at, and non-security bots are no longer shot at.
And yes, stun mode can kill spiders.
=> Makes turrets shoot hostile mobs and not shoot not-so hostile mobs

code/game/machinery/cryopod.dm, code/game/turfs/turf_changing.dm, code/modules/factions/faction.dm, code/modules/lighting/lighting_overlay.dm, code/modules/mob/living/silicon/robot/death.dm, code/modules/mob/new_player/new_player.dm, code/modules/modular_computers/file_system/programs/command/faction_core.dm, code/modules/world_save/map_storage.dm, nano/templates/faction_core.tmpl
=> Cryo network system, bug fixes for shuttles, lighting

code/game/objects/items/weapons/storage/bags.dm, nano/templates/faction_core.tmpl
=> template fix, trash bag rebalance

code/game/turfs/turf_changing.dm, code/modules/factions/faction.dm, code/modules/modular_computers/file_system/programs/command/faction_core.dm, nano/templates/faction_core.tmpl
=> Accesses by rank

code/modules/factions/faction.dm, code/modules/modular_computers/file_system/programs/command/faction_core.dm
=> Access by rank part 2

code/game/objects/items/weapons/cards_ids.dm
=> access by rank part 3

nano/templates/identification_computer.tmpl
=> template fix

code/modules/modular_computers/file_system/programs/command/card.dm
=> Record fixeroni

code/modules/client/preference_setup/general/05_background.dm, code/modules/client/preferences_savefile.dm, code/modules/modular_computers/file_system/programs/research/email_administration.dm, code/modules/world_save/map_storage.dm
=> New characters start with email, email now saves

code/game/area/Space Station 13 areas.dm, code/modules/lighting/lighting_turf.dm, code/modules/modular_computers/file_system/programs/command/faction_core.dm, code/modules/power/power.dm, test/run-test.sh
=> Small fixes

code/datums/supplypacks/hospitality.dm, code/datums/supplypacks/materials.dm, code/datums/supplypacks/miscellaneous.dm, code/datums/supplypacks/supply.dm
Tinkers with base material costs to further encourage multi-departmental working to generate funds.
Decreases cost of miscellaneous objects that have no game impact but are purely decorative to give people simple things to purchase and generally giving a single ethercoin some buying power.
=> Pricechanges

code/game/machinery/cryopod.dm, code/modules/factions/faction.dm
=> small cryopod fix

code/controllers/configuration.dm, code/modules/admin/admin.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/topic.dm, code/modules/client/preference_setup/preference_setup.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/new_player/new_player.dm
=> Creates a system for player rewards, like bonus slots

code/game/objects/items/weapons/cards_ids.dm, code/modules/factions/bluespace_satellite.dm, code/modules/factions/faction.dm, code/modules/modular_computers/file_system/programs/command/card.dm, code/modules/modular_computers/file_system/programs/command/faction_core.dm, nano/templates/bluespacesatellite.tmpl, nano/templates/faction_core.tmpl
=> Adds tags for IDs

code/game/gamemodes/gameticker.dm, code/game/machinery/cryopod.dm, code/modules/mob/new_player/new_player.dm, code/modules/world_save/map_storage.dm
=> Makes characters save at their location

code/modules/modular_computers/file_system/programs/command/buisness.dm, nano/templates/buisness_control.tmpl
=> buisness template fix

code/modules/modular_computers/file_system/programs/command/buisness.dm, nano/templates/business_control.tmpl
=> More fixes

code/modules/modular_computers/file_system/programs/command/buisness.dm, nano/templates/business_control.tmpl
=> more changes

code/modules/world_save/map_storage.dm
=> Mayhaps definitely possibly fixes character nullspace saving

code/controllers/employment_controller.dm, code/modules/factions/faction.dm, code/modules/modular_computers/file_system/programs/command/buisness.dm, nano/templates/business_control.tmpl
=> even more additions

code/modules/factions/bluespace_satellite.dm, code/modules/modular_computers/file_system/programs/command/card.dm, code/modules/modular_computers/file_system/programs/command/faction_core.dm, code/modules/modular_computers/file_system/programs/medical/clone_manager.dm, nano/templates/bluespacesatellite.tmpl, nano/templates/business_control.tmpl, nano/templates/cloning_management.tmpl, nano/templates/faction_core.tmpl
=> Factions now cost 10000, Clones cost 5000

code/modules/factions/bluespace_satellite.dm, code/modules/modular_computers/file_system/programs/command/buisness.dm, nano/templates/bluespacesatellite.tmpl, nano/templates/business_control.tmpl
=> Business and Faction price adjustment

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/silicon/robot/life.dm, code/modules/organs/internal/stack.dm
=> more robot fix

code/controllers/ambience.dm, code/modules/modular_computers/file_system/programs/command/card.dm
=> ambience music update

code/modules/modular_computers/file_system/programs/command/faction_core.dm, nano/templates/faction_core.tmpl
=> adds sales tax menu option

code/game/machinery/cryopod.dm, code/modules/modular_computers/file_system/programs/command/buisness.dm, code/modules/modular_computers/file_system/programs/command/card.dm, code/modules/world_save/map_storage.dm
=> Laces and Robots in cryo! Map improvements!

code/game/machinery/cryopod.dm
=> and a small fix

code/modules/mining/drilling/drill.dm
=> balance maybe

code/controllers/aggression_controller.dm, code/modules/mining/drilling/drill.dm, code/modules/mining/mine_turfs.dm
=> more balance

code/controllers/aggression_controller.dm, code/modules/mining/drilling/drill.dm, code/modules/mining/mine_turfs.dm, code/modules/mob/living/simple_animal/hostile/creature.dm, code/modules/mob/living/simple_animal/hostile/voxslug.dm
=> important lighting fix

code/_onclick/hud/skybox.dm
=> and a inv fix

code/game/machinery/doors/airlock_electronics.dm
=> fix airlock electronics (roops)

code/game/objects/structures/janicart.dm, code/game/supplyshuttle.dm, code/modules/mob/living/carbon/brain/MMI.dm, code/modules/modular_computers/file_system/programs/command/card.dm, code/modules/organs/internal/stack.dm, code/modules/reagents/reagent_containers/food/snacks.dm
=> Account mod fix. Export fix.

code/datums/supplypacks/supply.dm, code/game/machinery/adv_med.dm, code/game/turfs/simulated/wall_icon.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/reagents/reagent_dispenser.dm
Description fix for walls. Sanity checks for bodyscanners. Made reagent_dispensers correctly state why they can't be deconstructed. Re-purposed salvage voidsuits as a cheaper alternative for people to buy from supply
=> Various Changes

code/game/machinery/cryopod.dm
=> cryopod fix (roops)

code/game/machinery/cryopod.dm, code/game/supplyshuttle.dm
=> adds bracket

code/game/machinery/cryopod.dm, code/game/supplyshuttle.dm
=> removes bracket

code/modules/mob/new_player/new_player.dm, code/modules/random_map/automata/caves.dm
=> 100000 /mob/new_players and a plated asteroid

code/controllers/ambience.dm, code/game/area/areas.dm, code/modules/organs/internal/heart.dm, code/modules/organs/internal/lungs.dm
=> sound changes

code/game/objects/items/devices/radio/encryptionkey.dm
=> fix captains encryption key

code/game/atoms_movable.dm
=> Fixes Z throw

code/datums/supplypacks/materials.dm
Increases phoron import price for 10 sheets to 1.5k, equal to export of 10 sheets at 150.
=> Increase phoron price to match export price

code/game/objects/items/weapons/cards_ids.dm, code/game/supplyshuttle.dm, code/modules/factions/bluespace_satellite.dm, code/modules/mob/living/carbon/lace/lace.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/modular_computers/file_system/programs/generic/supply2.dm, code/modules/organs/internal/stack.dm
=> fixes shuttle access, cyborg access and clock in, supply access

code/modules/mob/living/simple_animal/hostile/voxslug.dm, code/modules/organs/internal/stack.dm
=> Glutslug burrow rate reduce, runtime fix

code/game/antagonist/outsider/actors.dm, code/game/objects/items/weapons/cards_ids.dm, code/modules/organs/internal/stack.dm
=> fixes robot access and clock in

code/modules/mob/living/simple_animal/simple_animal.dm
=> fixes dead animal icons

code/_onclick/cyborg.dm
=> removes borg hotkeys

code/modules/organs/internal/stack.dm
=> duty status fix

code/modules/admin/admin_report.dm, code/world.dm
=> hopeful visibility fix

code/game/machinery/teleporter.dm, code/game/objects/items/weapons/cards_ids.dm, code/modules/materials/materials_ore.dm
=> hub visible fix? business expense card fix

code/game/gamemodes/gameticker.dm, code/modules/mob/new_player/new_player.dm
=> Fixes admins aghosting creating bodies on save

code/game/objects/items/weapons/soap.dm, code/game/turfs/simulated/wall_icon.dm
=> Makes walls merge

code/controllers/employment_controller.dm, code/game/machinery/teleporter.dm, code/game/objects/items/robot/robot_parts.dm, code/game/turfs/simulated/wall_icon.dm, code/modules/organs/internal/stack.dm, code/modules/research/designs.dm
=> Fixes compiler errors, reworks employment_controller

code/controllers/employment_controller.dm
=> Stops runtime, makes it not pay so much

code/controllers/employment_controller.dm, code/game/objects/items/robot/robot_upgrades.dm, code/modules/client/preferences.dm
This reverts commit 87c8cb736caf89a07ddb733b09c91e91cf32e0c5.
=> Revert "fix cryo reversions... and pay"

code/modules/client/preferences.dm, code/modules/mob/new_player/new_player.dm
=> more revert

code/modules/organs/external/head.dm, code/modules/organs/external/standard.dm, code/modules/organs/internal/heart.dm, code/modules/organs/internal/liver.dm, code/modules/organs/internal/lungs.dm
Reverts Persistent-SS13/Persistent-Bay#437 as it breaks surgeries. Prehaps a damage reduction should be added to the organs take_damage instead
=> Revert "Healthier Spessmen"

code/game/machinery/cryopod.dm, code/modules/client/preferences.dm, code/modules/modular_computers/file_system/programs/medical/clone_manager.dm
=> more cryo fix

code/modules/client/preferences.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/modular_computers/file_system/crew_record.dm
=> fix promotions,

code/modules/client/preferences.dm
=> Just a syntax error from previous pull

code/game/machinery/wall_frames.dm, code/game/objects/structures/watercloset.dm
Makes it so when you dismantle sinks, toilets, etcetra you get back plastic instead of steel.
=> Plumbing plastic

code/modules/reagents/Chemistry-Recipes.dm
They were all kindsa fucked (only one worked and it made the wrong kinda material), and from what I can tell it's just because someone copy/pasted and didn't change the reaction names.
First PR, possible fuckups ahead
=> Fixes material-creating reactions

code/modules/modular_computers/file_system/crew_record.dm
=> probably promote fixx

code/modules/modular_computers/file_system/crew_record.dm
=> add indent

code/controllers/employment_controller.dm, code/modules/modular_computers/file_system/crew_record.dm
=> moer pay fix

code/controllers/aggression_controller.dm, code/modules/mining/drilling/drill.dm, code/modules/mob/living/simple_animal/hostile/voxslug.dm, code/modules/random_map/noise/ore.dm
=> my anger is your fucking hardship

code/datums/supplypacks/hospitality.dm, code/datums/supplypacks/science.dm, code/game/objects/items/weapons/basketball.dm
Most notable addition is the $$3000 R&D crate, which contains circuit boards for an R&D server, protolathe, destructive analyzer, circuit imprinter, and autolathe, as well as accompanying computers. Athletics crate enables you to play basketball and beat the bejeezus out of each other, hopefully not at the same time. First time doing real code edits for SS13, so i might've messed stuff up, but I don't think so.
=> Adds R&D Crate and Athletics Crate

code/controllers/aggression_controller.dm, code/modules/mining/drilling/drill.dm, code/modules/mob/living/simple_animal/hostile/voxslug.dm, code/modules/random_map/noise/ore.dm
This reverts commit d3d6cba8ee1b72e5b42f19a3513be6852f8f7c76.
=> the asteroid receds.. for now.

code/modules/organs/internal/stack.dm
=> fix lace weirdness..

code/controllers/subsystems/mapping.dm, code/datums/mind.dm, code/modules/admin/admin.dm, code/modules/admin/admin_report.dm, code/modules/client/preferences.dm, code/modules/modular_computers/file_system/crew_record.dm, code/world.dm
=> email fix proc, bug fix, allows visibility

code/game/mecha/mecha.dm
=> makes mechs not save

code/modules/client/preferences.dm
=> more fix, the big fix the fix is in

code/modules/mob/new_player/new_player.dm
=> more fixmore fix

code/modules/client/preferences.dm, maps/vignette/vignette.dm
=> fix verticle zlevels, increase pick speed

code/game/machinery/cryopod.dm, code/game/machinery/rechargestation.dm, code/modules/mob/new_player/new_player.dm, code/modules/organs/internal/stack.dm
=> possibly fixes the cryo bug

code/modules/mining/machinery/mineral_processor.dm, code/modules/organs/internal/stack.dm
=> fix mineral processor, fix runtimes

code/datums/supplypacks/atmospherics.dm, code/datums/supplypacks/engineering.dm, code/datums/supplypacks/medical.dm, code/datums/supplypacks/operations.dm, code/datums/supplypacks/science.dm, code/datums/supplypacks/security.dm, code/datums/supplypacks/supply.dm, code/modules/clothing/spacesuits/spacesuits.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/clothing/spacesuits/void/void.dm, code/modules/xenoarcheaology/tools/equipment.dm
adds an "upgraded" spacesuit of each job type (except science) to cargo, also some price adjustments & adds magboots to the softsuit crate.
=> More spacesuits in cargo + basic tiering

code/controllers/aggression_controller.dm, code/modules/materials/definitions/materials_mineral.dm, code/modules/materials/material_sheets.dm, code/modules/materials/materials_ore.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/mob_defines.dm
Fixes a few compilation errors with phoronation. A future PR will include Phoron Reconstructant Syndrome  and phoron-bone deposits.
=> Fixes phoronation.

code/game/machinery/biogenerator.dm
biogen overhaul, needed for the future autotailor. Wood, cardboard are extras I added.
=> added cloth leather cardboard and wood to the biogen. overhauuuuul:)

code/game/machinery/cryopod.dm
=>  Forgot this

code/__defines/chemistry.dm, code/controllers/aggression_controller.dm, code/game/machinery/frame.dm, code/game/objects/items/weapons/circuitboards/other.dm, code/game/objects/items/weapons/storage/backpack.dm, code/game/shuttle_engines.dm, code/modules/client/preferences.dm, code/modules/materials/definitions/materials_mineral.dm, code/modules/materials/materials_ore.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/simple_animal/hostile/voxslug.dm, code/modules/mob/mob_defines.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm, code/modules/research/designs.dm
=> revert the revert 

code/controllers/aggression_controller.dm, code/modules/materials/definitions/materials_mineral.dm, code/modules/materials/material_sheets.dm, code/modules/materials/materials_ore.dm, code/modules/mob/living/carbon/human/life.dm
Fixes a few compile errors caused by commit reversions
=> Fixes phoronation compile errors

code/modules/reagents/reagent_containers.dm
=> Fixes 100% chance of spilling when transferring reagents from a holder to holer

code/game/turfs/turf_changing.dm, code/modules/mob/new_player/new_player.dm
=> fixes new_player runtime and better shuttle movement

code/modules/designer/designer.dm, html/designer.html, persistentss13.dme
Anyone ripping this code better credit it back to Persistent and myself bechez
=> The Designer feature

code/modules/integrated_electronics/core/saved_circuits.dm, code/modules/mob/mob_helpers.dm
Fix 2 bugs:
- Circuit analyzers not creating proper saves
- The number 0 not being able to be input into a circuit debugger
=> Fix IC saving and debugger input

code/controllers/configuration.dm, config/example/config.txt, interface/interface.dm, interface/skin.dmf, persistentss13.dme
Adds a Donation and Discord Button to the Rpane
=> Donation and Discord Buttons

code/modules/mob/new_player/new_player.dm, code/modules/organs/internal/_internal.dm, code/modules/organs/internal/lungs.dm
=> fixxe spam

code/game/machinery/alarm.dm
=> Fixed air alarms partially resetting settings when game loads

code/game/machinery/alarm.dm, code/game/machinery/autolathe.dm
=> fix infinite autolathe

code/__defines/subsystem-priority.dm, code/controllers/subsystems/processing/mobs.dm, code/modules/mob/mob.dm, code/modules/mob/mob_defines.dm
Lets take this with a grain of salt. Should be heavily monitored once it goes live.
Subsystem_defines.dm to perhaps increase the overall mob's priority (i decreased from 100 to 50 since users are still at 100.) but it can have unexpected shit from monsters like being too easy ? We'll see.
=> Adds new subsystem for user mob processing - Decreases other mob's process priority

code/datums/supplypacks/medical.dm
_Vindictive_ change to encourage players to get each other donating blood.
=> Time to hold a blood drive

code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
Allow those w/core access security programs to use Warrant Assistant. This fixes an issue where no one is able to use Warrant Assistant.
=> Fix Warrant Assistant

code/modules/mob/mob.dm
=> Fixes the new subsystem not letting you create a new character 

code/__defines/subsystem-priority.dm, code/controllers/subsystems/processing/mobs.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/mob.dm, code/modules/mob/mob_defines.dm
=> Reverts my own shit. New SS for hostile mobs only for seperated, lower priority processing

code/game/machinery/doors/simple.dm, code/game/objects/items/blueprints.dm, code/modules/materials/_materials.dm, code/modules/materials/definitions/materials_glass.dm, code/modules/materials/definitions/materials_metal.dm, code/modules/materials/definitions/materials_mineral.dm, code/modules/materials/definitions/materials_organic.dm, code/modules/materials/definitions/materials_other.dm, code/modules/materials/definitions/materials_stone.dm, code/modules/tables/tables.dm
=> Updates tables and blueprints

code/modules/mining/machinery/mineral_processor.dm
=> Ore processor should no longer eat your shit.

code/game/turfs/turf_changing.dm, code/modules/mining/drilling/drill.dm, code/modules/mob/living/simple_animal/hostile/creature.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/voxslug.dm, code/modules/overmap/exoplanets/desert.dm, code/modules/random_map/noise/ore.dm
=> more fix!!

code/controllers/subsystems/processing/mobs.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm
=> REVERT HOSTILE SS (In case we need)

code/modules/materials/definitions/materials_organic.dm
Add hardness and weight values distinct from default (60) to cloth, leather etc
=> No cloth bats or leather knives

code/modules/mining/satchel_ore_boxdm.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/random_map/noise/ore.dm
=> more attempted fix..

code/modules/mob/living/simple_animal/hostile/hostile.dm
=> fix runtime

code/game/mecha/mecha.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/overmap/exoplanets/desert.dm, code/modules/random_map/noise/ore.dm
=> ore generation fix

code/game/objects/structures/barsign.dm, code/modules/overmap/exoplanets/desert.dm
=> further tunes ore generation

code/modules/item_worth/materials.dm, code/modules/mob/living/simple_animal/hostile/bat.dm, code/modules/mob/living/simple_animal/hostile/creature.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm
=> Few more asteroid changes

code/game/objects/items/blueprints.dm, code/game/supplyshuttle.dm, code/modules/item_worth/reagents.dm, code/modules/research/designs.dm
=> rebalances existing exports bigtime

code/game/mecha/mecha.dm, code/game/objects/items/blueprints.dm, code/game/objects/structures/barsign.dm, code/game/supplyshuttle.dm, code/modules/item_worth/materials.dm, code/modules/item_worth/reagents.dm, code/modules/mob/living/simple_animal/hostile/bat.dm, code/modules/mob/living/simple_animal/hostile/creature.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/overmap/exoplanets/desert.dm, code/modules/research/designs.dm
=> Rebalances Exports

code/game/supplyshuttle.dm
=> whoopz 2.0

code/controllers/aggression_controller.dm, code/game/objects/items/blueprints.dm, code/modules/overmap/exoplanets/desert.dm
=> turn back on monsters!! ahhhh!!!

code/game/objects/items/blueprints.dm, code/modules/modular_computers/file_system/programs/generic/supply2.dm
=> fix blueprints

code/modules/materials/material_recipes.dm
This allows Silent Celestine to craft the rolling pin.
=> Add craftable rolling pin

code/modules/modular_computers/computers/subtypes/dev_laptop.dm
- You can no longer close laptops with your mind if they are placed
- You can now close laptops that are in your bag
=> Laptops should make more sense

code/datums/supplypacks/security.dm, code/game/objects/items/devices/holowarrant.dm, code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
- Warrant Assistant will now check for either Security or Command access.
- Holowarrants can be swiped by a Security member or Command member (your station can decide who is actually authorized to sign off on warrants)
- Holowarrant crate is $500 and contains 4 warrant projectors.
=> More holowarrant fixes, holowarrant crate

code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/organs/subtypes/skrell.dm
A small organ in the heads of Skrell.
=> Add Skrell nerve cluster

tgui/src/interfaces/jukebox.ract
Fix the jukebox to be similar to https://github.com/rhicora/Persistent-Bay/blob/877e11dfdc9e8bf99697daa71c17738de100686d/nano/templates/jukebox.tmpl
=> Fix jukebox

nano/templates/supply.tmpl
=> Fix supply

code/modules/modular_computers/file_system/programs/generic/supply2.dm
Fixes some things related to revoke
=> Fix feedback msg for revoke

code/modules/paperwork/handlabeler.dm
=> Also delabel turfs

code/game/machinery/jukebox.dm
=> Possibly fix jukebox to use nanoui

code/game/machinery/jukebox.dm
=> More jukebox fixes

code/controllers/employment_controller.dm, code/game/machinery/jukebox.dm
=> jukebox changes

code/datums/supplypacks/medical.dm
Add two new supplypack:
-Bandage Pack Crate contain: 10 Bandages. 15 each. 150$ for the crate.
-Advance Trauma Kit Crate : 10 Trauma Kit. 30 each. 300$ for the crate.
Not sure about the objects name i a have just done some copy paste and some editing.
Tell me were i can find all the objects name please.
=> Update new supplypacks.

code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
I'm not sure what's wrong with Warrant Assistant but at the moment no one can use it.
=> Remove Warrant Assistant checks

code/modules/world_save/map_storage.dm
=> zlevel fixxez

code/modules/integrated_electronics/core/pins.dm, code/modules/world_save/map_storage.dm
=> more fixs.

code/modules/world_save/map_storage.dm
=> adds breakout

code/modules/world_save/map_storage.dm
=> skip zlevel 29

code/modules/world_save/map_storage.dm
=> potential fix

code/modules/world_save/map_storage.dm
=> try to merge to two zlevels..

code/modules/events/event_container.dm, code/modules/events/event_dynamic.dm, html/changelogs/UndeadNappist-pr-729.yml, maps/vignette/vignette_define.dm
Hopefully removes the grid_check / power outage event from the game.
=> Removes power outage

code/modules/world_save/map_storage.dm
=> makes dev great again (sans changelog)

code/modules/mob/new_player/new_player.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/modular_computers/file_system/programs/command/buisness.dm, nano/templates/business_control.tmpl
=> Fix Naked Spawns, lower business cost to 2500

code/controllers/communications.dm, code/datums/supplypacks/medical.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/weapons/implants/implants/death_alarm.dm, code/modules/mob/living/say.dm, code/modules/research/message_server.dm, code/modules/scripting/Implementations/Telecomms.dm
Adds the Trauma Alarm, which works like a death alarm but alerts on any of the following:
- The client's `blood_oxygenation` is less than 60.
- The client's `oxygen_damage` is greater than 35.
- The client's `toxin_damage` is greater than 35.
=> Trauma team features

code/modules/shuttles/shuttle.dm, code/modules/shuttles/shuttle_console.dm
=> fixes horrific shuttle accidents.

code/modules/mob/new_player/new_player.dm
=> fixes players spawning without clothing

code/modules/mob/new_player/new_player.dm
=> compile time fix

code/game/machinery/hologram.dm, html/changelogs/rhicora-pr-770.yml
These are long-range holopads, and don't care which Z they're connecting to!
=> Allow long distance holocalls

code/game/objects/structures/stasis_cage.dm
=> Fixes not being able to pickup small animals

code/game/machinery/recycler.dm
Reverts Persistent-SS13/Persistent-Bay#773
=> Revert "Do not qdel cortical stacks in the Recycler"

code/controllers/employment_controller.dm
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
=> employment controller fix

nano/templates/docking_beacon.tmpl
=> fix public beacons

code/modules/world_save/map_storage.dm
=> stability improvements part 1

code/modules/world_save/map_storage.dm
=> save improvements part 2

code/modules/admin/admin.dm, code/modules/admin/admin_verbs.dm
=> adds spacejunk deleter

code/modules/admin/admin.dm
=> fuck me up chuck

code/controllers/employment_controller.dm, code/game/machinery/cryopod.dm, code/game/machinery/portable_turret.dm, code/modules/admin/admin.dm, code/modules/admin/admin_verbs.dm, code/modules/emotes/definitions/_mob.dm, code/modules/world_save/map_storage.dm, nano/templates/docking_beacon.tmpl
=> Main-To-Dev merge

code/game/machinery/portable_turret.dm
=> Fixes a runtime I forgot

code/modules/economy/Accounts.dm
=> erase debug spam

code/game/machinery/portable_turret.dm, code/modules/economy/Accounts.dm, code/modules/factions/faction.dm, code/modules/world_save/map_storage.dm
=> Main to Dev REEE BRAWLER

code/modules/admin/admin.dm, code/modules/factions/faction.dm
=> ,pre sadawawda

code/modules/ZAS/Zone.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm, code/modules/xgm/gases.dm, code/modules/xgm/xgm_gas_data.dm
TO-DO: explanation.. Im too tired as of writing this
=> SoM Hotfix 1 - Adds base boiling point to some

code/controllers/subsystems/garbage.dm, code/modules/ZAS/Zone.dm
=> main stability fix

code/controllers/subsystems/garbage.dm, code/modules/ZAS/Zone.dm, code/modules/admin/admin.dm, code/modules/atmospherics/atmos_primitives.dm, code/modules/mob/new_player/new_player.dm, code/modules/xgm/xgm_gas_data.dm
=> pushes dev to main

code/game/machinery/atmoalter/canister.dm, code/modules/atmospherics/components/binary_devices/dp_vent_pump.dm, code/modules/atmospherics/components/unary/outlet_injector.dm, code/modules/atmospherics/components/unary/vent_pump.dm
=> remove condensation

html/changelogs/ingles98-pr-890.yml, test/run-test.sh
=>  Fixes changelogs and globals

html/changelogs/ingles98-pr-890.yml, test/run-test.sh
=> Dev to Main

html/changelogs/ingles98-pr-890.yml, test/run-test.sh
Reverts Persistent-SS13/Persistent-Bay#907
=> Revert "Dev to Main"

code/controllers/master.dm
=> Makes the master controller start itself.

code/modules/economy/Accounts.dm, code/modules/factions/faction.dm, code/modules/world_save/map_storage.dm
=> more pay debugging

code/modules/world_save/map_storage.dm
=> record fix

code/modules/world_save/map_storage.dm
=> slight fix

code/modules/economy/Accounts.dm
=> accounts fix

code/modules/world_save/map_storage.dm, test/check-paths.sh
=> Updates Travis

code/modules/admin/admin.dm, code/modules/economy/Accounts.dm, code/modules/projectiles/targeting/targeting_mob.dm, code/modules/world_save/map_storage.dm
=> makes accounts fix

code/modules/mob/new_player/new_player.dm, code/modules/modular_computers/file_system/programs/generic/id_management.dm, code/modules/world_save/map_storage.dm
=> travizZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

code/modules/modular_computers/file_system/programs/command/card.dm
Cleaned up from my previous PR.
=> Admin ghost can now change job assignment
