Persistent-SS13/Persistent-Bay

code/game/machinery/alarm.dm
code/modules/atmospherics/components/unary/vent_pump.dm
code/modules/atmospherics/components/unary/vent_scrubber.dm
nano/templates/air_alarm.tmpl

Allows you to toggle a vent from pressurize to syphon from an air alarm as well.

Allows a multitool to force-broadcast vents and scrubbers.

---

code/datums/supplypacks/medical.dm

Adds in specific first-aid supply crates so you don't need to order the Medical Crate for 5 other items you won't use, the crates are more expensive than the regular Medical Crates despite giving less total items. That is an intentional drawback, blame how Central Command's Supply department organizes things.

Adds in specific first-aid crates to Supply Management

---

code/modules/organs/external/Phorosian.dm

burn damage multiplier is more deadly than I thought it would be. Not touching that, instead giving them small bonuses to keep with the theme of being made out of a tougher but more flammable material.
- Breathing phoron reduces lung damage
Of course you're still gonna die if you run out.
- Breathing phoron replenishes blood
Seeing as blood packs don't (and wouldn't make sense to) exist for them and oxygen restoring drugs just hurt them, they gain a very slow blood gain when breathing phoron. They will still bleed out if shanked/shot/burned.
- Breaking point of bones increased by five points of damage

Quick phorosian buff

---

code/modules/mob/living/carbon/human/species/outsider/vox.dm
code/modules/organs/internal/heart.dm

Fixes a bug where hearts won't stop. This can lead to massive heart damage from adrenaline.
Also fixes a bug where Vox have human organs, which could cause some weird situations occasionally.
These fixes were taken from the following Bay PRs:
https://github.com/Baystation12/Baystation12/pull/19878
https://github.com/Baystation12/Baystation12/pull/20440

Fixes a Couple of Organ Bugs

---

code/modules/reagents/reagent_containers/syringes.dm

This PR cleans up syringe code a lot and makes it so you can inject chems into people who are inside stasis bags.
Stolen from the following Baystation PR:
https://github.com/Baystation12/Baystation12/pull/19865

Cleans up syringe code, injecting into stasis bags

---

code/modules/hydroponics/seed_datums.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/organs/external/_external.dm
code/modules/organs/external/_external_damage.dm
code/modules/organs/internal/_internal.dm
code/modules/organs/internal/kidneys.dm
code/modules/organs/internal/liver.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm

Liver now builds up toxins (ammonia) instead of dealing straight damage when it's hurt. This can be combated with dialysis.
Kidneys work similarly, but they build up potassium, which can be dangerous if left unchecked, and increases heart rate.
Bananas now have a little potassium.
Internal organs no longer take damage twice from bullets, and ribs provide a little protection.
Now you can see bones when you have wounds that would be considered retracted, and ascertain the state of organs by looking at them, instead of having to scan the patient to see that their lungs aren't supposed to look like that.
This PR is based on the following Baystation12 PRs:
https://github.com/Baystation12/Baystation12/pull/20856
https://github.com/Baystation12/Baystation12/pull/20857 …

Organ Tweaks

---

code/modules/modular_computers/file_system/manifest.dm

It pretty much just strikes off anyone who's considered "Inactive"

Crew Manifest Will Now Only Show Active Players

---

code/modules/mob/living/carbon/human/species/outsider/vox.dm

Due to air tanks being nerfed (from 3 hours to about 45 minutes), I think it's fair that Vox get filter masks, so they don't have to constantly use their precious reserve.
These masks filter out oxygen in the air, letting Vox breathe easy on Human stations.

Gives Vox Filtering Masks on Spawn

---

code/game/machinery/camera/camera_assembly.dm

NanoTrasen-Brand Security Cameras are automatically networked for your convenience!

New cameras feed to nt_net instead of Exodus

---

code/datums/supplypacks/operations.dm
code/game/objects/structures/crates_lockers/closets/secure/personal.dm

You can order them in the Operations section of supply, and they arrive empty. First scanned ID card assigns their name to the locker, and after that, only they will be able to use it. Crew with Core Command Programs access may override a locker's assignment and reset its ownership.

Add personal lockers, patient closets, cabinets

---

code/datums/supplypacks/hospitality.dm
code/datums/supplypacks/miscellaneous.dm
code/game/objects/items/weapons/cigs_lighters.dm
code/game/objects/items/weapons/storage/boxes.dm
code/game/objects/items/weapons/storage/fancy.dm
code/modules/materials/material_recipes.dm

The imported cigarettes crate gives you a random group of branded cigarettes and/or lighters, but this is pretty expensive. The gambling crate gives you cards and dice. You can now use cardboard to make cigarette packs, cartons, and hand-rolled cigarettes. Dip them in a reagent to finish them.

Add imported cigs, custom cigs, and gambling

---

code/__defines/machinery.dm
code/game/machinery/camera/presets.dm
code/modules/modular_computers/file_system/programs/generic/camera.dm
maps/vignette/vignette.dm
maps/vignette/vignette_presets.dm

What I'm trying to do:
- Add the 'nt_net' and 'freenet' security camera networks for each of the default factions.
- Require security program access (5) in the appropriate faction to access.
- Add a 'Public' network for public broadcasts.
- Add a 'Television' program which does nothing but consume Public cameras.
What I'm not trying to do:
- Add full camera support for custom factions.

Fix the camera system to allow public and starter faction cams

---

code/game/supplyshuttle.dm

Quick patch to supply shuttles. They'd toss a runtime if the path for their thing didn't exist. This would cause Travis to fail on unrelated PRs like #106

Supply Shuttle Fix

---

code/controllers/employment_controller.dm

This code change causes refugees and other factions to be paid. They will get back pay for the time worked since that will have been logged as "worked" in their crew record.
982a513 caused payday timer to advance by one hour immediately upon issuing pay. Since NT was the first faction in the list, this was absolutely no problem for them, but by the time Refugee was evaluated, it had already become "not payday yet."

Pay Refugees

---

code/datums/supplypacks/supply.dm
code/modules/power/lighting.dm

- Uses unique names for the colored bulb crate vs. the colored tube crate
- Makes color of each bulb / tube apparent in the name

Patch for Colored Lights

---

code/game/objects/items/devices/tvcamera.dm
code/modules/modular_computers/NTNet/NTNet.dm
code/modules/modular_computers/file_system/programs/generic/camera.dm

This patches some issues with Television and Camera Monitor.
- Public network is now viewable on Camera Monitor in addition to Television
- Press camera drones now broadcast to public channel
- Software list can be refreshed by turning NTNet downloads off and on again

Patch for Televisions / Cameras

---

code/game/machinery/autolathe_datums.dm
code/modules/reagents/reagent_dispenser.dm

Adds autolathe recipes for the following: pitcher, carafe, coffee cup (all types), spray bottle, dropper, ecigarette, beer keg, water cooler. Fixes inconsistent capitalization in autolathe recipes.

More autolathe recipes

---

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
code/modules/reagents/Chemistry-Recipes.dm

- Fixes Adrenaline bug where Adrenaline increases the players pulse twice after wearing off.
- Changed Rezadone's recipe, now requires Arithrazine inside of Carpotoxins (In order to make it usable in a Carp-less frontier) 
- Removed Clonexadone's and Cryoxadone's organ healing properties due to balancing reasons.

[WIP] Fixes Adrenaline bug, changes to Rezadone recipe and Clonex/Cryoxa

---

code/__defines/items_clothing.dm
code/game/machinery/computer/prisoner.dm
code/game/machinery/kitchen/smartfridge.dm
code/game/machinery/teleporter.dm
code/game/objects/items.dm
code/game/objects/items/weapons/storage/belt.dm
code/game/objects/items/weapons/tape.dm
code/game/objects/items/weapons/towels.dm
code/modules/clothing/spacesuits/breaches.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/mob_helpers.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/stun.dm
code/modules/projectiles/projectile/beams.dm
code/modules/projectiles/projectile/energy.dm

Ports all the misc stuff on my "To Port" list.
Fixes Tracking Implants so they're Multi-Z Capable
Fixes tracking implants not showing in the target list
Make items dried in the drying rack brownish instead of gray
Duct tape can temporarily reseal spacesuits
Allow wearing of belts even with no jumpsuit
Weapon effect balancing and hit chance balancing
Shamelessly stolen from the following Bay PRs:
https://github.com/Baystation12/Baystation12/pull/19734
https://github.com/Baystation12/Baystation12/pull/19886
https://github.com/Baystation12/Baystation12/pull/20026
https://github.com/Baystation12/Baystation12/pull/20067
https://github.com/Baystation12/Baystation12/pull/20175
https://github.com/Baystation12/Baystation12/pull/20756
https://github.com/Baystation12/Baystation12/pull/20787

Numerous Misc Ports

---

code/modules/mob/mob.dm
interface/skin.dmf

Shift+WASD in hotkey mode allows you to "throw" your eye (arrows/numpad also work).
Allows 5 extra turfs of sight in the chosen direction.
Works for diagonals too.
Should obey rules of visibility as that's done from the PoV from your mob.

Added peeking (shift + dir / alt + WASD)

---

code/game/machinery/autolathe_datums.dm
code/game/objects/items/weapons/ecigs.dm
code/modules/modular_computers/file_system/programs/generic/supply2.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
code/modules/reagents/Chemistry-Recipes.dm

- Adds adrenaline reaction (1 Adrenaline, 1 Hyperzine, 1 Hydrochloric Acid), which allows you to synthesize more epinephrine given a sample.
- Synthetic adrenaline is still dangerous for your heart and stacks with what the body naturally produces.
- Nerfs Rezadone and makes it a Ryetalyn derivative. Please don't use this drug if you don't have to, it will mess people's faces up.
- Fix a typo in exports.
- Fix vape sprites.

Add epinephrine reaction, fix ecigs and export text

---

code/_helpers/global_access.dm
code/_helpers/time.dm
code/controllers/configuration.dm
code/game/gamemodes/events/holidays/Holidays.dm
config/example/config.txt
test/run-test.sh

Year skip and Timezone are config options. Roundstart time is now equal to the current time GMT +- timezone hours. 
Year skip default has been set to 420 years, down from baycode's 544, and up from our lore's 400. It's 420 because that syncs up perfectly with the Gregorian calendar's cycle, so the calendar will be exactly the same as the real current year's.
Timezone default has been set to EST (GMT-5) because /shrug

Makes Time Configurable, Links IC time to realtime

---

code/modules/materials/materials.dm
code/modules/reagents/Chemistry-Machinery.dm

Materials can now be ground into multiple reagents and can have different amounts of each reagent per sheet.
Kept the old grinding recipes, and also added a few more:
Ice to water and ice
Dry ice to carbon
Iron to iron
Steel to iron and carbon
Plastic to plasticide
Wood to a little carbon
Phoron-glass to a little phoron

Reworks Material Grinding

---

code/modules/factions/faction.dm
code/modules/modular_computers/file_system/programs/generic/invoicing.dm
nano/templates/faction_core.tmpl
nano/templates/supply.tmpl

This change will allow stations to control import access independently. Exports and invoicing will no longer be access-controlled, since all you can do with these things is make money for the station.
- The Send Exports tab no longer requires admin authentication
- The Invoicing program no longer requires admin authentication
- The `core_access_order_approval` permission is now called "Import Approval" instead of "Import/Export Approval"

Access control Imports only

---

code/game/objects/items/weapons/tanks/tank_types.dm

Oxygen tanks (full size) now has a full 10xpressure in it by default.
Anesthetic:
*Now start full
*Modified volume to match default tanks instead of being super meta by having a higher potential volume
*Hopefully won't explode
*Defaults to a distribute pressure so people won't suffocate automatically when you try using it on them

default gas tank gas amounts

---

code/_helpers/global_access.dm
code/datums/supplypacks/materials.dm
code/game/machinery/autolathe.dm
code/game/machinery/autolathe_datums.dm
code/game/objects/items/weapons/circuitboards/broken.dm
code/game/objects/items/weapons/circuitboards/circuitboard.dm
code/game/objects/items/weapons/circuitboards/machinery/cargo.dm
code/game/objects/items/weapons/circuitboards/machinery/cloning.dm
code/game/objects/items/weapons/circuitboards/machinery/cryopod.dm
code/game/objects/items/weapons/circuitboards/machinery/mech_recharger.dm
code/game/objects/items/weapons/circuitboards/machinery/pacman.dm
code/game/objects/items/weapons/circuitboards/machinery/power.dm
code/game/objects/items/weapons/circuitboards/machinery/research.dm
code/game/objects/items/weapons/circuitboards/other.dm
code/modules/materials/material_sheets.dm
code/modules/mining/mine_items.dm
code/modules/power/cable.dm
code/modules/research/designs.dm
code/modules/research/stock_parts.dm
code/unit_tests/autolathe_tests.dm
persistentss13.dme
test/run-test.sh

The autolathe can now take any stacked material and print with any material. There is also a couple new Travis tests that ensures all autolathe recipes are valid.
To showcase this, I've added some circuits that take various precious metals (copper, silver, gold, platinum); the kind of stuff you'd need to start up a station before you can get an R&D department running.
I eventually plan to port over most handcrafted recipes to the autolathe, and give it a category system that isn't garbage.

Reworks Autolathe, Adds Autolathe Recipe Tests to Travis

---

code/modules/client/client_defines.dm
code/modules/client/client_procs.dm
code/modules/world_save/map_storage.dm

In an effort to reduce RAM use, I'm going to be trying a number of things to split the files. This makes records and factions stored in a records.sav file, I've already tested the full system, but I need to merge it in three parts because I need to first
Have the server load like it used to, but save with the new files generated, then
Merge the other half and restart, so that the load now uses the new files and not the old save, and finally
Make the final change which takes the old unnecessary save protocols out, this is saved for last so that any files created prior to this are valid backups.

Save improvement Part 1/3, Saving Records as its own file

---

code/game/machinery/doors/airlock.dm

In addition, opening the panel without access will produce a visible message, making it obvious what you're doing. Hopefully will discourage grey-tide hacking.

Adds a delay to airlock panel opening if the player does not have access

---

code/game/machinery/autolathe.dm
code/game/machinery/autolathe_datums.dm
code/game/machinery/machinery.dm
code/game/machinery/recycler.dm
code/game/objects/items.dm
test/check-paths.sh

Added multiplier to machinery. 
Implemented multiplier for autolathe. 
Fixed wire coil recipe.
Fixed poor math on autolathe recipe. 
Fixed autolathe using an ancient window method. 
Allowed autolathe to take any material. 
Buffed autolathe storage and crafting speed.
Recycler now eats materials of items and spits out sheets of the correct stuff. 
Recycler doesn't recycle any type of stack.
Increased default item spread.

Nice autolathe + sane recycler

---

code/_helpers/unsorted.dm
code/controllers/subsystems/processing/processing.dm
code/datums/weakref.dm
code/game/images.dm
code/game/objects/effects/spiders.dm
code/modules/admin/admin_secrets.dm
code/modules/admin/secrets/debug/world_types.dm
code/modules/blob/blob.dm
code/modules/lighting/lighting_atom.dm
code/modules/mob/living/carbon/human/npcs.dm
code/modules/mob/living/say.dm
code/modules/mob/mob.dm
persistentss13.dme

To enable debugging:
- Click subsystem in the MC tab, this opens the VV window
- In the drop-down menu in the upper right select "Call Proc"
- Enter "toggle_debug", press OK, finish argument input
- Excess running times should now result in runtimes.
Shamelessly stolen from https://github.com/Baystation12/Baystation12/pull/19962
Ported this debug tool as well, which gets type counts: https://github.com/Baystation12/Baystation12/pull/21856
Also ports these bugfixes and tweaks from bay:
https://github.com/Baystation12/Baystation12/pull/19998
https://github.com/Baystation12/Baystation12/pull/20046
https://github.com/Baystation12/Baystation12/pull/20128
https://github.com/Baystation12/Baystation12/pull/20123
https://github.com/Baystation12/Baystation12/pull/20427 …

Ports Bugfixes and Debug Tools From Bay

---

code/game/machinery/portable_turret.dm
code/modules/mob/living/bot/secbot.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/mob_helpers.dm
code/modules/modular_computers/file_system/crew_record.dm
code/modules/modular_computers/file_system/programs/generic/records.dm

Criminal status applied with security HUDs and other future methods now properly reads from faction records, so turrets and security bots will only pew-pew at the people _their_ faction sets as criminals.
In addition, a Faction-ID check will prevent anyone unauthorized from changing criminal status, unless they steal the necessary ID.
The modular-computer records program now reads from the faction records, and far more of the fields (including security/medical/employment records and criminal status) are now available to those with the right access.

Factionalized wanted status and records program functionality

---

code/modules/mob/living/carbon/human/species/species.dm
code/modules/mob/living/carbon/human/species/station/station.dm
code/modules/mob/living/carbon/human/update_icons.dm
code/modules/power/apc.dm

APCs are now given a Terminal on initial map-start.
Fixed a bug where Unathi clothing was offset when laying down
(code taken from https://github.com/Baystation12/Baystation12/pull/20707)

APC Terminals and Unathi Clothing fix

---

code/modules/organs/external/head.dm
code/modules/organs/external/standard.dm
code/modules/organs/internal/heart.dm
code/modules/organs/internal/liver.dm
code/modules/organs/internal/lungs.dm

Buffs the health of the Head, Chest, Lungs, Liver, and Heart to more realistic degrees.
It does not modify internal hemorrhaging or damage over time due to broken bones.
The head and chest are now EXTREMELY difficult to break or shatter, especially compared to the arms, feet, and hands.
In short, you will still take damage over time from internal injuries and broken bones, which will accumulate, and de-limbing but not dying is now easier.

Healthier Spessmen

---

code/modules/emotes/definitions/audible.dm
code/modules/emotes/definitions/visible.dm

Ported from https://github.com/Baystation12/Baystation12/pull/22892
More emotes are now targetable, and previously broken targeted emotes are not functional

Ports emote fixes from Bay.

---

code/game/machinery/autolathe_datums.dm
code/modules/paperwork/paper.dm
code/modules/projectiles/guns/projectile/detective.dm
code/modules/projectiles/guns/projectile/revolver.dm

I removed the mind.assigned.role restrictions on using the clown stamp and renaming the .38 revolver, because persistence doesn't really use mind roles. I considered doing the same thing for the Chaplain requirement making holy water with a bible and water tank, but I didn't really know if there is anything planned in that regard so I left it as is.
Also, fixes #480

Removes Mind Role Restrictions in some cases

---

code/game/shuttle_engines.dm

Another simple self explanatory bug fix. Was asking for stacks of uranium rather than sheets.

Makes shuttle engines not banish uranium stacks to the void

---

code/game/objects/items/robot/robot_upgrades.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/reagents/reagent_containers/borghydro.dm
code/modules/research/mechfab_designs.dm

Phoron costs for Mining borgs completely removed as to not cause instances where there isn't enough phoron for new miners, because there isn't enough miners to mine phoron. Phoron costs also removed for various service modules, and reduced for both Engineering and Medical modules. Module costs re-adjusted for various modules, mining module now requires uranium.
Chassis Modules now cost silver instead of phoron as to have people start using them to customize.
Security borg module should now spawn modules, security borgs already created will need their module re-installed.
Added in the Standard borg, along with accompanying chassis mods. The Standard cyborg now has a Inaprovline autoinjector for stabilizing persons in need, along with a metal synthesizer to make floor tiles.

Edits module cost values, fixes Security borgs spawning with no modules, and adds standard borg.

---

code/game/jobs/access.dm
code/game/machinery/doors/airlock.dm
code/game/machinery/doors/airlock_electronics.dm
code/modules/modular_computers/file_system/programs/command/buisness.dm

Adds new access level for business to be used on the business airlock electronics.
Fixes probably everything with the airlock electronics, we can forget that this code even exists.
Added two new defines for ease-of-change's sake (was actually done like this cause i had custom access' in mind at the beginning)
Locked business electronics can only be unlocked by someone who has access (ACCESS_BUSINESS_ELETRONICS ) and belongs to the business that locked it.
Locking it with no access choosen will make it unlockable by someone else.

Fixes all airlock electronics related stuff

---

code/game/objects/items/weapons/storage/storage.dm

Should fix some issues regarding boxes that have a preset 'startswith = list(...)' which would have its content's delayed upon spawning and therefore no max_w_class and max_storage_space (which is set right on Initialize, after spawn() but still before its statements run)
If this 10 seconds delay is REALLY NECCESSARY (i don't see how it is to be honest) then i'll work it around making an max_w_class and max_storage_space update followed by an UI update. Didn't go with that easier fix because a 10 seconds delay is plain dumb, it actually makes newly spawned boxes (or those straight from cargo) only have items on it after 10 seconds. There are few boxes that have different items on them, which is what "startswith" list does, different from other boxes which use only one item type on them so …

Fixes the box mixedglasses' UI, and probably other box's as well

---

code/game/objects/items/devices/radio/electropack.dm
code/game/objects/structures/electricchair.dm
code/game/objects/structures/stool_bed_chair_nest/chairs.dm

Had to re-create since the other one got stormed by merge commits and what not and im dumb
**ELECTRIC CHAIRS CAN ONLY BE MADE _STRICTLY_ ON A NORMAL STEEL CHAIR** (/obj/structure/bed/chair)

Fixes electric chair functionality AND duplication glitch

---

code/modules/reagents/Chemistry-Recipes.dm

Prevents players from manufacturing chemsmoke due to the fact, with recent updates, it could probably be used to make infinite anything.
Including explosions.
Does _not_ remove chemical smoke from the game - merely the recipe for it in chemistry.

Comments out chemsmoke

---

code/modules/mob/living/simple_animal/friendly/lizard.dm
code/modules/surgery/slimes.dm

Not really nerfs. When a slime runs out of cores, it should self-delete, and hopefully I'm not a moron and spawning runtimes again.
Similarly, lizards now have /meat/ added to their typing as a list of reagents, which should enable butchering.

Slime nerfs

---

code/modules/mob/new_player/new_player.dm
code/modules/modular_computers/file_system/programs/command/faction_core.dm

Prefer the following order for cryopod spawn:
1. Assignment cryonet for the cryo'd person's primary faction
2. Wherever the cryo'd person despawned last time
3. Default cryopods for the cryo'd person's primary faction

Fix cryonet to use last cryopod

---

code/game/objects/items/weapons/cards_ids.dm
code/modules/paperwork/papershredder.dm

- Expense cards can now be shredded
- ID and expense cards can now be melted
- ID and expense cards can now be cut up with wirecutters

More ways to destroy cards

---

code/modules/mob/living/carbon/human/say.dm

Prevents whispers from incorrectly displaying (e.g. `"Things look weird when I&#39;m whispering."`).
Ports https://github.com/Baystation12/Baystation12/commit/3e18d67c5778c1caed006db1a2fb7c07ca88087f

Fix whispers

---

code/modules/modular_computers/file_system/programs/generic/supply2.dm
nano/templates/supply.tmpl

As a Supply Program user, if you have `core_access_command_programs` for the faction, you can use the Admin menu. The admin menu allows you to revoke the connection of rogue telepads.
Also fixes a bug where all possible import pads were selected if it didn't know which to use.

Remotely revoke telepads

---

code/modules/mob/living/carbon/human/species/station/human_subspecies.dm

Players who are whitelisted for Vatgrown test subjects can play them. This won't affect anyone for now since no one has this whitelist.

Add whitelist for vatgrown humans

---

code/modules/paperwork/handlabeler.dm

Allows admins to `spawn /obj/item/weapon/hand_labeler/admin_delabeler`
This item can be used to clean up after label grief. To use it, simply attack a badly-labeled object with it. It will delabel this object as well as any others on the server with the same label.

Admin delabeler for cleaning up label grief

---

nano/templates/crew_monitor_map_content.tmpl

This removes the `rank-` class from Crew Monitoring, which was causing a bug.

Fix the crew monitor bug

---

code/game/machinery/portable_turret.dm
html/changelogs/rhicora-pr-769.yml

Makes turrets not shoot borg friends unless they meet the same criteria as humans to get shot.
This duplicates https://github.com/Persistent-SS13/Persistent-Bay/pull/705, which was approved for main but got stepped on at some point during a revert.

Fix borgos in main

---

code/game/machinery/bioprinter.dm

This reverts commit a9aa3ccdf8a534eeeacd4032263cd1ed8db39495.
It is horrible to have the roboprinter nonfunctional. As such, I am doing a revert on this specific file. I will later get it to use OCP like I originally intended - but in my opinion, not having it available to players is worse at this time. Future fixes are to follow.
It has been fully tested and the roboprinter works without issues.

Revert "Update bioprinter.dm"

---

code/game/machinery/recycler.dm

Recycler was set up to avoid deleting nuke auth disks and ... material stacks?!
I think they meant cortical stacks (laces).
Fixes https://github.com/Persistent-SS13/Persistent-Bay/issues/772

Do not qdel cortical stacks in the Recycler

---

code/modules/mob/living/silicon/robot/robot_modules.dm

Engineering borgs have this var that allows them to traverse tiles without gravity, this should function exactly like that.

Allows mining borgs to traverse the asteroid

---

code/game/machinery/pipe/construction.dm
code/game/objects/structures/windoor_assembly.dm
code/game/objects/structures/window.dm
code/modules/power/singularity/emitter.dm
code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
code/modules/recycling/disposal-construction.dm

Changed objects changed in the alt-click addition, not sure if more are affected, added 
if(!usr || !Adjacent(usr))
return
if(usr.incapacitated())
return
to said files under the rotate() function, should terminate the function if the player acting on it is not beside, or is incapacitated.
#774

Fixed Rotation Range (And Rotating While Incapacitated)

---

code/game/machinery/portable_turret.dm

Currently, turrets will not shoot at any borgos if set to "check access". In this merge, check their access.

Properly identify borgos that don't have access

---

code/modules/world_save/map_storage.dm

This fixes the issue with the map not loading, caused by a check for the file game.sav which is not created or used anywhere in the code.

Map loading fix
